### ISSUE TITLE
No way to import the module in bundler (i.e. Webpack)

### ISSUE THREAD

**Issue by pmrotule** [ctf0/vue-multi-ref#1]
Currently assuming that `Vue` exists as a global variable. Would be great to have a way to use it with Webpack by importing the module, something like:
```js
import Vue from 'vue'
import VueMultiRef from 'vue-multi-ref'

Vue.use(VueMultiRef)
```

**Comment by ctf0** [comment]
sadly i dont know how to do the `Vue.use()` , if you know plz send me a PR

**Comment by pmrotule** [comment]
Actually, my bad, we could not use `Vue.use()` since it is not a plugin, but a directive. It would still be possible to set the directive on the `vue` module itself. See https://github.com/ctf0/vue-multi-ref/pull/2
