### ISSUE TITLE
Jest > TypeError: Cannot read property 'directive' of undefined

### ISSUE THREAD

**Issue by cassiofelippe** [ctf0/vue-multi-ref#3]
Error in unit test (using jest) when trying to import it.

> TypeError: Cannot read property 'directive' of undefined

`import 'vue-multi-ref';`

> at Object.<anonymous> (node_modules/vue-multi-ref/src/index.js:34:5)
---
I've also tried not to import, but then get this error:
> [Vue warn]: Failed to resolve directive: multi-ref

Is there a way to unit test components that use vue-multi-ref?

Thanks!

**Comment by ctf0** [comment]
the error u r getting is about https://github.com/ctf0/vue-multi-ref/blob/ad5c1473bf543e9024fd0b854486776ccb159d42/src/index.js#L34

which is related to 
https://github.com/ctf0/vue-multi-ref/blob/ad5c1473bf543e9024fd0b854486776ccb159d42/src/index.js#L32

so u either add vue like `import Vue from 'vue'` or `window.Vue = require('vue')` b4 u import the directive

**Comment by cassiofelippe** [comment]
I am already importing Vue before 'vue-multi-ref' in my test and in my main.js, still getting the error.

`TypeError: Cannot read property 'directive' of undefined`

      1 | import Vue from 'vue';
    > 2 | import 'vue-multi-ref';
        | ^
      3 | 
      4 | 
      5 | 

`
      at Object.<anonymous> (node_modules/vue-multi-ref/src/index.js:34:5)
      at Object.<anonymous> (tests/jest/input-identificacao.test.js:2:1)
`

**Comment by ctf0** [comment]
i might need to do more testing but try
```
import Vue from 'vue';
window.Vue = Vue

import 'vue-multi-ref'
```

**Comment by cassiofelippe** [comment]
Unfortunately it didn't work, I didn't believed it would because I haven't used at any moment window.Vue in my application.
If it's possible for you to run some tests, so I can at least know if is something you'll need to fix or is a specific problem of mine.
I'll be waiting for a response, thanks!

**Comment by ctf0** [comment]
@pmrotule do u also have this issue ?

**Comment by cassiofelippe** [comment]
A possible workaround to this issue is to add this ``` Vue.directive('multi-ref', {}) ``` to the test file.
But I'm having issues while trying to work with the refs in my tests, don't know if it's possible, still trying to find a way.

**Comment by cassiofelippe** [comment]
Yep, it worked. In my case I was using the multi-ref to a child component, so I stubbed it and it rendered as I expected.

**Comment by cassiofelippe** [comment]
Reopening because there is still a problem. I can run my tests with no problem adding the directive in the test file, the problem is that the refs won't be rendered. The only way out I found yet was adding the functions to the test: ``` Vue.directive('multi-ref', {bind: addRef, update: addRef, unbind: removeRef}); ``` and declaring the functions.
Still need something to be done in the lib.

**Comment by pmrotule** [comment]
@CassioFelippe We had the exact same issue at work and we solved it by exporting the directive config in order to define it for our app, but also within Jest:

*multi-ref directive*
```js
export default {
  bind: addRef,
  update: addRef,
  unbind: removeRef,
}
```

*app settings*
```js
import Vue from 'vue'
import MultiRefDirective from '@/directives/multi-ref'

Vue.directive('multi-ref', MultiRefDirective)
```

*test helper*
```js
import { createLocalVue as _createLocalVue } from '@vue/test-utils'
import MultiRefDirective from '@/directives/multi-ref'

export function createLocalVue() {
  const localVue = _createLocalVue()
  localVue.directive('multi-ref', MultiRefDirective)
  ...
```

The thing is, we had to stop using the `multi-ref` module so I agree with you, it should be supported. It would be also a better solution to deal with having `Vue` set globally vs within Webpack.

@ctf0 What do you think? It would involve breaking changes though.

**Comment by ctf0** [comment]
does this happen with every directive u both have in ur app or only with the multi-ref ?

if the later, am not sure what to be done with the directive as it follows the same structure as the docs.

@pmrotule could u make a new branch with the new changes needed and share it with us ? maybe we can release 2 versions to cover all cases

**Comment by cassiofelippe** [comment]
I've experienced this problem only with multi-ref.

What I did to be able to run my tests is to create a test-helper that sets the directive, something like this:

```
import Vue from 'vue'

Vue.directive('multi-ref', {
  bind: addRef,
  update: addRef,
  unbind: removeRef
});
```
